# Generated by Django 5.2.9 on 2026-01-06 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nama Bisnis')),
                ('category', models.CharField(blank=True, max_length=100, null=True, verbose_name='Kategori')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Alamat')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='No. HP/WA')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Website Saat Ini')),
                ('has_website', models.BooleanField(default=False, verbose_name='Punya Web?')),
                ('rating', models.FloatField(default=0.0, verbose_name='Rating GMaps')),
                ('reviews_count', models.IntegerField(default=0, verbose_name='Jumlah Review')),
                ('status', models.CharField(choices=[('NEW', 'New Lead (Belum Diapa-apain)'), ('CONTACTED', 'Sudah Dihubungi'), ('PROPOSAL', 'Kirim Proposal'), ('DEAL', 'Deal / Closing'), ('REJECT', 'Ditolak')], default='NEW', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
