# Generated by Django 5.2.9 on 2026-01-06 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Kantor'),
        ),
        migrations.AddField(
            model_name='lead',
            name='tech_stack',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Teknologi Web'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='reviews_count',
            field=models.IntegerField(default=0, verbose_name='Jml Review'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='Link Website'),
        ),
    ]
